### ISSUE TITLE
Converted AVIF files larger than source images

### ISSUE THREAD

**Issue by vsuvarna** [fdintino/pillow-avif-plugin#11]
I have a small concern regarding this plugin. I'm using it to convert jpegs pulled from the internet to avif images. In doing so, the operation is performed successfully, but the resulting file is often larger than the source jpeg. One key reason I was converting the images is to reduce file size and save bandwidth. I would appreciate any insight or help as to why this is happening. Is there a step I'm doing incorrectly or does the plugin need a fix.

Here's the code I'm using:
```
#Save poster files
poster_small_image = requests.get(poster_small_url)
with open(f'.\TMDB_posters_jpeg\small\\{movie_id}.jpeg', 'wb') as f:
          f.write(poster_small_image.content)

poster_medium_image = requests.get(poster_medium_url)
with open(f'.\TMDB_posters_jpeg\medium\\{movie_id}.jpeg', 'wb') as f:
          f.write(poster_medium_image.content)

#Convert to AVIF
with Image.open(f'.\TMDB_posters_jpeg\medium\\{movie_id}.jpeg') as poster_medium_jpeg:
    poster_medium_jpeg.save(f'.\TMDB_posters_avif\medium\\{movie_id}.avif')

with Image.open(f'.\TMDB_posters_jpeg\small\\{movie_id}.jpeg') as poster_small_jpeg:
    poster_small_jpeg.save(f'.\TMDB_posters_avif\small\\{movie_id}.avif')
```
Thank you.

**Comment by fdintino** [comment]
Like any of the other image codecs, the size of the file is determined by the arguments passed to `save`, the most important of which is `quality`. [See these docs](https://github.com/python-pillow/Pillow/blob/cc4afabba3853ec62e5190045466476eb795bd45/docs/handbook/image-file-formats.rst#avif) for a complete list of the options that can be passed to `save()` for AVIF images.

This comes up often enough in the issues that I should perhaps decrease the default quality.
