### ISSUE TITLE
Some files are not recognized.

### ISSUE THREAD

**Issue by alexsilva** [fdintino/pillow-avif-plugin#13]
Many "fox.profile..." files from sample repositories are not recognized
https://github.com/link-u/avif-sample-images

```
PIL.UnidentifiedImageError: cannot identify image file '.../plum-blossom-small-profile2-12bpc-yuv444-alpha-limited-monochrome.avif'
```
Is there any additional configuration to resolve this?

**Comment by CTimmerman** [comment]
Not sure if same type, but this and more AVIF files from https://www.rferl.org/a/russia-children-taken-ukraine/32527298.html aren't recognized:

[tiv_mhtml_image8_fail.zip](https://github.com/fdintino/pillow-avif-plugin/files/15321231/tiv_mhtml_image8_fail.zip)

**Comment by LewisCowlesMotive** [comment]
https://dsqze93rovfg.cloudfront.net/ekpqf6v4fvfzzn7ea2jgq7bxcu.avif is not recognised as an AVIF; but I see an AVIF header if I get it, and `raise_for_status`; and drop to a debugger to verify that the response status code is 200
