### ISSUE TITLE
.webp images are smaller then .avif above quality 60

### ISSUE THREAD

**Issue by beenetto** [fdintino/pillow-avif-plugin#16]
We’ve been noticing some unexpected behaviour when comparing image sizes between .webp and .avif image formats using the same .jpeg source image. The .avif images only start to get smaller bellow quality 60. We would expect that even at full quality the .avif files would be smaller. 
When we use imagemagick we can see that the .avif files is almost half of the size of the .webp. Is there anyway to tweak the parameters in pillow to achieve similar results without quality loss?

### Script:

```
from PIL import Image
import pillow_avif
import os.path

image_name = 'original.jpg'
orig_size = os.path.getsize(image_name)
q_list = [i for i in range(10, 101) if not i % 10]
for q in q_list:
    img: Image = Image.open('original.jpg')
    webp_name = f'pillow_converted_q_{q}.webp'
    avif_name = f'pillow_converted_q_{q}.avif'
    img.save(webp_name, quality=q)
    webp_size = os.path.getsize(webp_name)
    print(f'The {webp_name} Size: {orig_size} -> {webp_size} bytes @quality {q}')
    img.save(avif_name, quality=q)
    avif_size = os.path.getsize(avif_name)
    print(f'The {avif_name} Size: {orig_size} -> {avif_size} bytes @quality {q}')

```

### Output:

```
The pillow_converted_q_10.webp Size: 164098 -> 32312 bytes @quality 10
The pillow_converted_q_10.avif Size: 164098 -> 15178 bytes @quality 10
The pillow_converted_q_20.webp Size: 164098 -> 39628 bytes @quality 20
The pillow_converted_q_20.avif Size: 164098 -> 20702 bytes @quality 20
The pillow_converted_q_30.webp Size: 164098 -> 47272 bytes @quality 30
The pillow_converted_q_30.avif Size: 164098 -> 26964 bytes @quality 30
The pillow_converted_q_40.webp Size: 164098 -> 55780 bytes @quality 40
The pillow_converted_q_40.avif Size: 164098 -> 36708 bytes @quality 40
The pillow_converted_q_50.webp Size: 164098 -> 64072 bytes @quality 50
The pillow_converted_q_50.avif Size: 164098 -> 62178 bytes @quality 50
The pillow_converted_q_60.webp Size: 164098 -> 71764 bytes @quality 60
The pillow_converted_q_60.avif Size: 164098 -> 97352 bytes @quality 60
The pillow_converted_q_70.webp Size: 164098 -> 80068 bytes @quality 70
The pillow_converted_q_70.avif Size: 164098 -> 123482 bytes @quality 70
The pillow_converted_q_80.webp Size: 164098 -> 103362 bytes @quality 80
The pillow_converted_q_80.avif Size: 164098 -> 149354 bytes @quality 80
The pillow_converted_q_90.webp Size: 164098 -> 163576 bytes @quality 90
The pillow_converted_q_90.avif Size: 164098 -> 193735 bytes @quality 90
The pillow_converted_q_100.webp Size: 164098 -> 312224 bytes @quality 100
The pillow_converted_q_100.avif Size: 164098 -> 550601 bytes @quality 100
```

### Using imagemagick:

`magick original.jpg magick.avif
`
```
-rw-r--r--   1 f.k  staff   53413 Oct 14 16:26 magick.avif
-rw-r--r--   1 f.k  staff  106618 Oct 14 16:28 magick.webp
```

**Comment by diegosuarez** [comment]
We're users of thumbor and we're using this plugin, we started converting some JPG images and saw just the related in this issue. There's a consistent oversize in AVIF files respecting webp, and using avifenc we're getting smaller images than its webp quality equivalent, as should be. Could it be some code bug in the quality management?

**Comment by fdintino** [comment]
AVIF images are compressed with parameters of maximum and minimum quantization, which doesn't exactly map over to the 0-100 quality used for JPEG and WEBP. I think I borrowed the logic from ImageMagick, but I'm not certain. The relevant code is here:

https://github.com/fdintino/pillow-avif-plugin/blob/616b64091fc3ec217c0458262ffcb5d22ce9d792/src/pillow_avif/AvifImagePlugin.py#L130-L143

My recommendation is to use a lower quality setting than you would for webp—somewhere between 60 and 75 (we use 75 on theatlantic.com). You'll also see better results if you use `rav1e` for encoding, as it produces smaller files than aom (the default encoder). This can be done by passing `codec="rav1e"` to the `save()` method, or in thumbor by setting `AVIF_CODEC = "rav1e"`.

In thumbor, you can use the `AVIF_QUALITY` setting to control the quality parameter for only AVIF files.

**Comment by diegosuarez** [comment]
Thank you Frankie, we'll take a look :-)
