### ISSUE TITLE
Build musllinux wheels for alpine users

### ISSUE THREAD

**Issue by ContinentalGuy** [fdintino/pillow-avif-plugin#2]
Hi, @fdintino !

I ran into an error while trying to save image.
```python
  File "/app/source/application/utils/resize.py", line 52, in save_image_to_buffer
    image.save(result, format=out_type, **save_kwargs)
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 2102, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.7/site-packages/pillow_avif/AvifImagePlugin.py", line 199, in _save
    is_single_frame,
RuntimeError: Failed to encode image: No codec available
```
Could you please help me to understand what package did i forget to install.

**Comment by ContinentalGuy** [comment]
```bash
$ /app/source # apk list -I | grep avif
.pillow-deps-avif-20210520.085254 noarch {.pillow-deps-avif} () [installed]
libavif-dev-0.9.0-r0 x86_64 {libavif} (BSD-2-Clause) [installed]
libavif-apps-0.9.0-r0 x86_64 {libavif} (BSD-2-Clause) [installed]
libavif-0.9.0-r0 x86_64 {libavif} (BSD-2-Clause) [installed]
$ /app/source # apk list -I | grep aom
aom-libs-1.0.0-r3 x86_64 {aom} (custom) [installed]
aom-1.0.0-r3 x86_64 {aom} (custom) [installed]
```

**Comment by fdintino** [comment]
What output do you get when you run the command `avifenc -V`?

**Comment by ContinentalGuy** [comment]
```sh
$ /app # avifenc -V
/bin/sh: avifenc: not found
```
🙂

**Comment by ContinentalGuy** [comment]
By the way, my microservice is running on alpine. I believe it is crucial for the issue, as when I moved the microservice to ubuntu, no "codec errors" appeared and everything went fine.

**Comment by ContinentalGuy** [comment]
Cannot find it in alpine [packages](https://pkgs.alpinelinux.org/contents?file=*avifenc*&path=&name=phoronix-test-suite&branch=edge&repo=testing&arch=ppc64le).

**Comment by fdintino** [comment]
It looks as though I'll probably need to build musllinux wheels. And to do that I may need to switch to cibuildwheel, which has musl support in its latest alpha release. I might keep the multibuild infrastructure in place (since it's the basis for some of my PRs to merge this into Pillow) even if I add cibuildwheel for alpine-compatible wheels.
