### ISSUE TITLE
Encoding with `Image.save(..., "AVIF")` fails

### ISSUE THREAD

**Issue by Sir-Photch** [fdintino/pillow-avif-plugin#23]
Hi,

on Ubuntu 20.04.1 LTS, I am getting the following error when trying to save an image with avif format:

```
>>> image.save("abc.avif")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/christoph/src/repos/encoder-trainer-py/.venv/lib/python3.8/site-packages/PIL/Image.py", line 2432, in save
    save_handler(self, fp, filename)
  File "/home/christoph/src/repos/encoder-trainer-py/.venv/lib/python3.8/site-packages/pillow_avif/AvifImagePlugin.py", line 235, in _save
    enc.add(
RuntimeError: Failed to encode image: Encoding of color planes failed
```

Since 20.04 does not provide libavif / libaom, I compiled them from source, versions being:
- libaom: v3.6.1
- libavif: v0.11.1

Are these the right versions / do I need other libraries as well?

**Comment by fdintino** [comment]
Are you able to encode the image using the `avifenc` command line utility?

**Comment by Sir-Photch** [comment]
Actually I wasn't, since libavif does not specify you have to enable additional apps like `avifenc` during manual build.

Anyway, I can now, but I still get the same error.

**Comment by mrrandom0110** [comment]
There is the same problem. Ubuntu 20.04. How to fix @fdintino ?

**Comment by una-dinosauria** [comment]
I ran into the same issue on CentOS 8 and 9. I am very confused by the error. It is being thrown by [this check](https://github.com/AOMediaCodec/libavif/blob/c7023c6b32e646020bb29c1eebac6c88f572ed9a/src/write.c#L1417-L1421) in libavif, which ensures that `avifEncoderAddImage` is only called once which -- and I've checked! -- the C wrapper in this repo does.

That particular `encoder->data->singleImage` variable should be initialized to `0 = AVIF_FALSE` on creation, and has no business being set to anything else elsewhere in the code, so I am wondering whether there is some nasty memory overwrite going on.

Like @Sir-Photch, I was able to compile `libavif` from scratch and I'm using the standalone `avifenc` without issues.

Unfortunately, github only provides ubuntu runners for linux so I cannot create a workflow that will reproduce the issue, but I'll try to reproduce this on a minimal docker image.

**Comment by fdintino** [comment]
What platform, architecture, and python version are you running? If there isn't a binary wheel available I can add one to CI.

**Comment by una-dinosauria** [comment]
CentOS 8 and 9. AMD x86_64, python 3.10. The wheel already exists for this combo. I tried to reproduce the issue on a docker image with CentOS but wasn't quite successful, sorry. I'll keep trying and let you know if I do achieve a successful repro.

**Comment by yit-b** [comment]
Ok! I found the cause. If you try to set encoder->numThreads to a value greater than 64, encoding fails. By default, pillow-avif-plugin sets numThreads to the number of cores on your machine. In my case, I have 96, so it will always fail.

Propose setting a limit of 64 returned from init_max_threads:
https://github.com/fdintino/pillow-avif-plugin/blob/main/src/pillow_avif/_avif.c#L52

**Comment by yit-b** [comment]
See this check in libavif source:
https://github.com/AOMediaCodec/libavif/blob/3ead1f3e99112871af0c52d4dc57a144d662b8cd/src/codec_aom.c#L750

**Comment by una-dinosauria** [comment]
Great sleuthing @yit-b! Do you plan to make a PR on `_avif.c`?

**Comment by yit-b** [comment]
@fdintino Please see PR #41
