### ISSUE TITLE
SVT-AV1 codec is using too much memory to process images

### ISSUE THREAD

**Issue by RaphaelVRossi** [fdintino/pillow-avif-plugin#39]
Hey @fdintino,

I did some tests with `pillow-avif-plugin` and `svt-av1` codec and after it the application not free the memory used. For each processed AVIF image the memory increase until reach the memory limit.

To replicate the test, please use this [gist](https://gist.github.com/RaphaelVRossi/e4fa2f502753b37a7d9d24448751cdf2) and follow the steps below:

```
docker build -t test-avif .

docker run -m 2g --cpus 1 -it -v "$(pwd):/app" test-avif2 bash

cd /app
wget https://live.staticflickr.com/1379/540719764_cddd076c3b_o_d.jpg  -O bug.jpg

/venv/bin/python3 process.py
```

You can use `docker stats` to monitore docker resources.

Could you please help me?! 🆘 

Thanks for all your support. 🎉

**Comment by RaphaelVRossi** [comment]
After an analysis, I managed to find where memory usage is increasing, this may help to find where is the problem.

```python
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
   123     67.9 MiB     67.9 MiB           1   @profile
   124                                         def _save(im, fp, filename, save_all=False):
   [...]
   233                                                         # Append the frame to the animation encoder
   234    714.6 MiB    633.8 MiB           2                   enc.add(
   235     80.9 MiB     12.9 MiB           1                       frame.tobytes("raw", rawmode),
   236     80.9 MiB      0.0 MiB           1                       frame_dur,
   237     80.9 MiB      0.0 MiB           1                       frame.size[0],
   238     80.9 MiB      0.0 MiB           1                       frame.size[1],
   239     80.9 MiB      0.0 MiB           1                       rawmode,
   240     80.9 MiB      0.0 MiB           1                       is_single_frame,
   241                                                         )   
   [...]
```

**Comment by fdintino** [comment]
SVT-AV1 unfortunately uses a lot of memory when encoding an image. And when you're encoding 10 images in parallel, as you are in your example script, it will use 10x that amount. You'll find that the memory gets released after all of the encodes are finished, though, so there isn't a memory leak here.

Using a higher SVT-AV1 preset / encoder mode (`speed` in libavif) will modestly reduce memory usage. You can use the highest preset mode by passing the kwarg `speed=10` to the save method. Though there is a bug in libavif that caps this value at 8 for the SVT codec, and the memory reduction is even more modest at 8 relative to the default. I've opened https://github.com/AOMediaCodec/libavif/pull/1824 with a fix for that.

**Comment by RaphaelVRossi** [comment]
Thank you @fdintino !

Using `speed=10` it really slightly reduced memory usage.

But when `enc.finish()` was called, no memory was released. You can see below:

```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
[...]
   234    587.9 MiB    506.7 MiB           2                   enc.add(
   235     81.2 MiB     10.9 MiB           1                       frame.tobytes("raw", rawmode),
   236     81.2 MiB      0.0 MiB           1                       frame_dur,
   237     81.2 MiB      0.0 MiB           1                       frame.size[0],
   238     81.2 MiB      0.0 MiB           1                       frame.size[1],
   239     81.2 MiB      0.0 MiB           1                       rawmode,
   240     81.2 MiB      0.0 MiB           1                       is_single_frame,
   241                                                         )
[...]
   252                                             # Get the final output from the encoder
   253    641.4 MiB     53.6 MiB           1       data = enc.finish()
   254    641.4 MiB      0.0 MiB           1       if data is None:
   255                                                 raise OSError("cannot write file as AVIF (encoder returned None)")
   256
   257    641.4 MiB      0.0 MiB           1       fp.write(data)
[...]
```

 Is that the correct behaviour?

**Comment by fdintino** [comment]
When running your script I've been using psutil to monitor memory usage of the running process. You can print out how many MB are being reserved for the process with:

```
print(psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)
```

I don't know much about the profile decorator you're using but I would try to rule that out as a cause of objects not getting released from memory.

**Comment by RaphaelVRossi** [comment]
I used this lib to profile memory https://pypi.org/project/memory-profiler/

But now I removed this profile decorator and use `psutil` to measure the memory.

```
python process.py
running
process 0
54.60546875
[log from svt]
631.2578125
finish
```

using this version of the script:

I'm currently running docker with Mac M1 and platform `linux/amd64`

```
import time
import asyncio

from PIL import Image

import pillow_avif
import gc
import psutil
import os

async def process(i):
    print("process", i)
    print(psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)
    await asyncio.sleep(1)
    with open("bug.jpg", "rb") as file:
        with Image.open(file) as image:
            image.save("bug.avif", "AVIF", codec="svt", quality=55, speed=10)



async def main():
    print("running")
    await asyncio.gather(*[process(i) for i in range(1)])
    print(psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)
    gc.collect()
    print(psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)
    print("finish")
    time.sleep(10)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

**Comment by fdintino** [comment]
I don't think there's anything actionable here, so I'm going to close it. But if you think I'm mistaken don't hesitate in reopening it. Thanks!
