### ISSUE TITLE
could not open avif file which generated by aom

### ISSUE THREAD

**Issue by MrWuZhenQuan** [fdintino/pillow-avif-plugin#47]
[img_2.zip](https://github.com/fdintino/pillow-avif-plugin/files/14902213/img_2.zip)
the zip include the avif image

**Comment by MrWuZhenQuan** [comment]
File "D:\anaconda3\lib\site-packages\PIL\Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'G:\\image-quality\\avif\\img_1.avif'

**Comment by fdintino** [comment]
This was fixed with the merge of #57, which was just uploaded to pypi in the 1.4.4 release.
